nodejs:
  image: 'hmctsprod.azurecr.io/juror/public:latest'
  applicationPort: 3000
  ingressHost: juror-public.{{ .Values.global.environment }}.apps.hmcts.net
  aadIdentityName: juror
  keyVaults:
    juror:
      secrets:
        - name: public-sessionSecret
          alias: public-sessionSecret
        - name: public-jwtKey
          alias: public-jwtKey
        - name: public-jwtNoAuthKey
          alias: public-jwtNoAuthKey
        - name: public-jwtKeyBureau
          alias: public-jwtKeyBureau
        - name: public-jwtTTL
          alias: public-jwtTTL
        - name: public-pcqTokenKey
          alias: public-pcqTokenKey
        - name: public-managedRedisConnection
          alias: public-redisConnection
        - name: public-dynatraceScriptUrl
          alias: public-dynatraceScriptUrl
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    API_ENDPOINT: https://juror-api.{{ .Values.global.environment }}.platform.hmcts.net/api/v1
    USE_AUTH: false
    TRACKING_CODE: ''
    SMARTSURVEY_API_ENDPOINT: https://api.smartsurvey.io/v1/surveys
    SMARTSURVEY_ID_V1: 301219
    SMARTSURVEY_ID_V2: 652997
    SMARTSURVEY_EXPORT_V1: Dashboard Export
    SMARTSURVEY_EXPORT_V2: Dashboard Export
    RATE_LIMIT_ENABLED: true
    RATE_LIMIT_TIME: 300000 # 5 minutes
    RATE_LIMIT_MAX: 1000000 # 1 mil requests
    REDIS_CLUSTER_ENABLED: true
